In [18]:
import pandas as pd
# 读取CSV文件，存储为DataFrame对象
file_path = r'D:\Desktop\Github\LAT-Repo\20230301\hwdata_2015.csv'
df = pd.read_csv(file_path)
# 显示DataFrame对象中的数据
df.head()

,RptNo,RptName,StatCourseNo,StatCourseName,DataDate,PlaceNo,PlaceName,PeriodNo,PeriodName,Complex1,...,Complex5,Complex5Name,DeriveNo,DeriveExplain,FValue,SValue,RptDeptNo,RptDeptName,CreateTime,ModifyTime
0,10430-01-02-2,臺中市高級中等學校校數及教職員數─按行政區別分,1043001a101,高級中等學校校數及教職員數─按行政區別分-校數(單位:所),2015/8/1 上午 12:00:00,10000066000010,臺中市中區,S,學年,230010000101,...,0,NaN,0,NaN,0,NaN,387040000E,教育局,2016/12/16 上午 09:33:33,NaN
1,10430-01-02-2,臺中市高級中等學校校數及教職員數─按行政區別分,1043001a101,高級中等學校校數及教職員數─按行政區別分-校數(單位:所),2015/8/1 上午 12:00:00,10000066000010,臺中市中區,S,學年,230010000102,...,0,NaN,0,NaN,0,NaN,387040000E,教育局,2016/12/16 上午 09:33:33,NaN
2,10430-01-02-2,臺中市高級中等學校校數及教職員數─按行政區別分,1043001a101,高級中等學校校數及教職員數─按行政區別分-校數(單位:所),2015/8/1 上午 12:00:00,10000066000010,臺中市中區,S,學年,2300100002,...,0,NaN,0,NaN,0,NaN,387040000E,教育局,2016/12/16 上午 09:33:33,NaN
3,10430-01-02-2,臺中市高級中等學校校數及教職員數─按行政區別分,1043001a101,高級中等學校校數及教職員數─按行政區別分-校數(單位:所),2015/8/1 上午 12:00:00,10000066000020,臺中市東區,S,學年,230010000101,...,0,NaN,0,NaN,2,NaN,387040000E,教育局,2016/12/16 上午 09:33:33,NaN
4,10430-01-02-2,臺中市高級中等學校校數及教職員數─按行政區別分,1043001a101,高級中等學校校數及教職員數─按行政區別分-校數(單位:所),2015/8/1 上午 12:00:00,10000066000020,臺中市東區,S,學年,230010000102,...,0,NaN,0,NaN,0,NaN,387040000E,教育局,2016/12/16 上午 09:33:33,NaN

In [21]:
import shutil

# 設定原始檔案路徑
src_file = "hw_20230308.ipynb"

# 設定目標資料夾路徑
dst_folder =  r"D:\Desktop\Github\LAT-Repo\20230308"

# 將檔案複製到目標資料夾
shutil.copy(src_file, dst_folder)

'D:\\Desktop\\Github\\LAT-Repo\\20230308\\hw_20230308.ipynb'

In [22]:
# 讀取第一列標題，並輸出所有欄位名稱
column_names = df.columns.tolist()
print(column_names)

['RptNo', 'RptName', 'StatCourseNo', 'StatCourseName', 'DataDate', 'PlaceNo', 'PlaceName', 'PeriodNo', 'PeriodName', 'Complex1', 'ComplexName', 'Complex2', 'Complex2Name', 'Complex3', 'Complex3Name', 'Complex4', 'Complex4Name', 'Complex5', 'Complex5Name', 'DeriveNo', 'DeriveExplain', 'FValue', 'SValue', 'RptDeptNo', 'RptDeptName', 'CreateTime', 'ModifyTime']

In [23]:
# 輸出每個欄位的 features
for column in df.columns:
    unique_values = df[column].unique()
    print(f"Column '{column}' has {len(unique_values)} unique values:\n{unique_values}\n")

Column 'RptNo' has 1 unique values:
['10430-01-02-2']

Column 'RptName' has 1 unique values:
['臺中市高級中等學校校數及教職員數─按行政區別分']

Column 'StatCourseNo' has 3 unique values:
['1043001a101' '1043001a102' '1043001a103']

Column 'StatCourseName' has 3 unique values:
['高級中等學校校數及教職員數─按行政區別分-校數(單位:所)' '高級中等學校校數及教職員數─按行政區別分-教師數(單位:人)'
 '高級中等學校校數及教職員數─按行政區別分-職員數(單位:人)']

Column 'DataDate' has 1 unique values:
['2015/8/1 上午 12:00:00']

Column 'PlaceNo' has 29 unique values:
[10000066000010 10000066000020 10000066000030 10000066000040
 10000066000050 10000066000080 10000066000060 10000066000070
 10000066000270 10000066000280 10000066000260 10000066000230
 10000066000090 10000066000150 10000066000200 10000066000100
 10000066000290 10000066000190 10000066000170 10000066000180
 10000066000160 10000066000240 10000066000130 10000066000250
 10000066000140 10000066000120 10000066000110 10000066000210
 10000066000220]

Column 'PlaceName' has 29 unique values:
['臺中市中區' '臺中市東區' '臺中市南區' '臺中市西區' '臺中市北區' '臺中市北屯區' '臺中市西屯區' '臺中市南屯區'
 '臺中市太平區' '臺中市大里區' '臺中市霧峰區' '臺中市烏日區' '臺中市豐原區' '臺中市后里區' '臺中市石岡區' '臺中市東勢區'
 '臺中市和平區' '臺中市新社區' '臺中市潭子區' '臺中市大雅區' '臺中市神岡區' '臺中市大肚區' '臺中市沙鹿區' '臺中市龍井區'
 '臺中市梧棲區' '臺中市清水區' '臺中市大甲區' '臺中市外埔區' '臺中市大安區']

Column 'PeriodNo' has 1 unique values:
['S']

Column 'PeriodName' has 1 unique values:
['學年']

Column 'Complex1' has 3 unique values:
[230010000101 230010000102   2300100002]

Column 'ComplexName' has 3 unique values:
['國立' '市立' '私立']

Column 'Complex2' has 3 unique values:
[         0 9900100001 9900100002]

Column 'Complex2Name' has 3 unique values:
[nan '男' '女']

Column 'Complex3' has 1 unique values:
[0]

Column 'Complex3Name' has 1 unique values:
[nan]

Column 'Complex4' has 1 unique values:
[0]

Column 'Complex4Name' has 1 unique values:
[nan]

Column 'Complex5' has 1 unique values:
[0]

Column 'Complex5Name' has 1 unique values:
[nan]

Column 'DeriveNo' has 1 unique values:
[0]

Column 'DeriveExplain' has 1 unique values:
[nan]

Column 'FValue' has 84 unique values:
[  0   2   1   3   4 103 223 163  96  72 191  49  79  38  87 170 164 137
 202 144 134 136  53  91  64 131  29  65  95  67  40  76 143 186  48  51
  74 295 399  47  68  98 155  94 168  60 101  58  25  37  46  70 108  14
  19  92  52  84  42  56  24  39  28  31  13  35   5  18  15  44   7  12
  20   6  23   8  21  10  11  17  36 125 107  99]

Column 'SValue' has 1 unique values:
[nan]

Column 'RptDeptNo' has 1 unique values:
['387040000E']

Column 'RptDeptName' has 1 unique values:
['教育局']

Column 'CreateTime' has 3 unique values:
['2016/12/16 上午 09:33:33' '2016/12/16 上午 09:33:34'
 '2016/12/16 上午 09:33:35']

Column 'ModifyTime' has 1 unique values:
[nan]

In [24]:
temp=df[["PlaceName","ComplexName",'Complex2Name','FValue']]
temp

    PlaceName ComplexName Complex2Name  FValue
0       臺中市中區          國立          NaN       0
1       臺中市中區          市立          NaN       0
2       臺中市中區          私立          NaN       0
3       臺中市東區          國立          NaN       2
4       臺中市東區          市立          NaN       0
..        ...         ...          ...     ...
428    臺中市大安區          國立            女       0
429    臺中市大安區          市立            男       0
430    臺中市大安區          市立            女       0
431    臺中市大安區          私立            男       0
432    臺中市大安區          私立            女       0

[433 rows x 4 columns]